package org.rai.interviewApp;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
@Entity
@Table(name="Person_Details_one_2_Many")
public class Person {     //Child class
	@Id
	@GeneratedValue
	private int personId;
	private String pesonName;
	private String address;
	private long personMob;
	@OneToMany(cascade = CascadeType.ALL)    //Third table will be generated by merging parent table and child table
	private List<Car> cars;
	public int getPersonId() {
		return personId;
	}
	public void setPersonId(int personId) {
		this.personId = personId;
	}
	public String getPesonName() {
		return pesonName;
	}
	public void setPesonName(String pesonName) {
		this.pesonName = pesonName;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public long getPersonMob() {
		return personMob;
	}
	public void setPersonMob(long personMob) {
		this.personMob = personMob;
	}
	public List<Car> getCars() {
		return cars;
	}
	public void setCars(List<Car> cars) {
		this.cars = cars;
	}
	
	
	

}
